"""Auto-generated PDF performance reports (fpdf2)."""

from __future__ import annotations

from pathlib import Path

from fpdf import FPDF

from deepiri_fuselk.reports.performance_report import PerformanceReport

# Deepiri control-room palette (matches port-view HUD; not a flat white dump).
_NAVY = (20, 26, 46)
_INK = (232, 236, 244)
_MUTED = (122, 138, 170)
_ACCENT = (68, 136, 255)
_PANEL = (16, 20, 31)
_LINE = (42, 51, 72)


class _PerfPDF(FPDF):
    def __init__(self, report: PerformanceReport) -> None:
        super().__init__(orientation="P", unit="mm", format="A4")
        self.report = report
        self.set_auto_page_break(auto=True, margin=18)
        self.set_margins(16, 16, 16)

    def header(self) -> None:
        self.set_fill_color(*_NAVY)
        self.rect(0, 0, self.w, 22, "F")
        self.set_text_color(*_INK)
        self.set_font("Helvetica", "B", 12)
        self.set_xy(16, 7)
        self.cell(0, 6, "deepiri-fuselk  ·  Performance Report", align="L")
        self.set_font("Helvetica", "", 8)
        self.set_xy(16, 13)
        self.set_text_color(*_MUTED)
        self.cell(0, 5, f"v{self.report.version}", align="L")
        self.ln(18)

    def footer(self) -> None:
        self.set_y(-14)
        self.set_draw_color(*_LINE)
        self.line(16, self.get_y(), self.w - 16, self.get_y())
        self.set_y(-12)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*_MUTED)
        self.cell(
            0,
            8,
            f"Page {self.page_no()}  ·  auto-generated  ·  {self.report.generated_at}",
            align="C",
        )


def render_performance_pdf(report: PerformanceReport, path: str | Path) -> Path:
    """Write a PerformanceReport to a branded A4 PDF. Returns the output path."""
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)

    pdf = _PerfPDF(report)
    pdf.add_page()

    # Title block
    pdf.set_fill_color(*_PANEL)
    pdf.set_draw_color(*_LINE)
    y0 = pdf.get_y()
    pdf.rect(16, y0, pdf.w - 32, 28, "DF")
    pdf.set_xy(20, y0 + 4)
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*_INK)
    pdf.multi_cell(pdf.w - 40, 7, _latin1(report.title))
    pdf.set_x(20)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*_MUTED)
    pdf.multi_cell(pdf.w - 40, 5, _latin1(report.subject))
    pdf.set_y(y0 + 32)

    # Thesis
    pdf.set_font("Helvetica", "I", 10)
    pdf.set_text_color(*_ACCENT)
    pdf.multi_cell(0, 5, _latin1(report.thesis))
    pdf.ln(4)

    if report.tags:
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*_MUTED)
        pdf.multi_cell(0, 4, _latin1("Tags: " + " · ".join(report.tags)))
        pdf.ln(3)

    for sec in report.sections:
        _section(pdf, sec)

    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*_MUTED)
    pdf.ln(4)
    pdf.multi_cell(0, 4, "Auto-generated by deepiri-fuselk performance report system.")

    pdf.output(str(out))
    return out.resolve()


def _latin1(text: str) -> str:
    """Map Unicode punctuation to Helvetica/latin-1 safe ASCII."""
    return (
        text.replace("\u2014", "-")  # em dash
        .replace("\u2013", "-")  # en dash
        .replace("\u2212", "-")  # minus
        .replace("\u2018", "'")
        .replace("\u2019", "'")
        .replace("\u201c", '"')
        .replace("\u201d", '"')
        .replace("\u2022", "*")
        .replace("\u00b7", "*")
        .replace("\u2192", "->")
        .replace("\u0394", "d")  # Greek Delta
        .replace("\u2206", "d")  # increment
        .encode("latin-1", errors="replace")
        .decode("latin-1")
    )


def _section(pdf: _PerfPDF, sec) -> None:
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*_INK)
    pdf.cell(0, 7, _latin1(sec.title), new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(*_ACCENT)
    pdf.set_line_width(0.4)
    y = pdf.get_y()
    pdf.line(16, y, 50, y)
    pdf.ln(3)

    if sec.narrative:
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_MUTED)
        pdf.multi_cell(0, 4.5, _latin1(sec.narrative))
        pdf.ln(2)

    if not sec.metrics:
        return

    # Table header
    col_w = [70, 35, 25, 50]
    pdf.set_fill_color(30, 38, 58)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*_INK)
    for i, h in enumerate(("Metric", "Value", "Unit", "Note")):
        pdf.cell(col_w[i], 6, h, border=0, fill=True)
    pdf.ln()

    pdf.set_font("Helvetica", "", 8)
    for idx, m in enumerate(sec.metrics):
        if pdf.get_y() > pdf.h - 24:
            pdf.add_page()
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_fill_color(30, 38, 58)
            pdf.set_text_color(*_INK)
            for i, h in enumerate(("Metric", "Value", "Unit", "Note")):
                pdf.cell(col_w[i], 6, h, border=0, fill=True)
            pdf.ln()
            pdf.set_font("Helvetica", "", 8)

        if idx % 2 == 0:
            pdf.set_fill_color(*_PANEL)
        else:
            pdf.set_fill_color(22, 28, 42)
        val = m.value if isinstance(m.value, str) else f"{m.value:.4g}"
        pdf.set_text_color(*_INK)
        row = [
            _clip(_latin1(str(m.name)), 42),
            _clip(_latin1(str(val)), 18),
            _clip(_latin1(str(m.unit)), 12),
            _clip(_latin1(str(m.note)), 28),
        ]
        for i, cell in enumerate(row):
            pdf.cell(col_w[i], 6, cell, border=0, fill=True)
        pdf.ln()


def _clip(text: str, n: int) -> str:
    text = text.replace("\n", " ").strip()
    return text if len(text) <= n else text[: n - 1] + "…"
