"""Unified performance report — KPIs physicists can export and cite."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from typing import Any


@dataclass
class PerformanceMetric:
    name: str
    value: float | str
    unit: str = ""
    note: str = ""


@dataclass
class PerformanceSection:
    title: str
    metrics: list[PerformanceMetric] = field(default_factory=list)
    narrative: str = ""


@dataclass
class PerformanceReport:
    """Auto-generated fuselk performance dossier (JSON / Markdown / PDF)."""

    title: str
    subject: str
    generated_at: str
    version: str
    thesis: str
    sections: list[PerformanceSection] = field(default_factory=list)
    tags: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def to_markdown(self) -> str:
        lines = [
            f"# {self.title}",
            "",
            f"**Subject:** {self.subject}  ",
            f"**Generated:** {self.generated_at}  ",
            f"**fuselk:** {self.version}",
            "",
            f"> {self.thesis}",
            "",
        ]
        if self.tags:
            lines.append("Tags: " + ", ".join(f"`{t}`" for t in self.tags))
            lines.append("")
        for sec in self.sections:
            lines.append(f"## {sec.title}")
            lines.append("")
            if sec.narrative:
                lines.append(sec.narrative)
                lines.append("")
            if sec.metrics:
                lines.append("| Metric | Value | Unit | Note |")
                lines.append("|--------|-------|------|------|")
                for m in sec.metrics:
                    val = m.value if isinstance(m.value, str) else f"{m.value:.4g}"
                    lines.append(f"| {m.name} | {val} | {m.unit} | {m.note} |")
                lines.append("")
        lines.append("---")
        lines.append("*Auto-generated by deepiri-fuselk performance report system.*")
        return "\n".join(lines)


def _now() -> str:
    return datetime.now(UTC).isoformat()


def from_workbench(report: Any, *, version: str) -> PerformanceReport:
    """Build a PerformanceReport from a ShotWorkbench WorkbenchReport."""
    cf = report.counterfactual
    closed = report.closed_loop.to_report()
    sections = [
        PerformanceSection(
            title="Counterfactual (closed − open loop)",
            narrative=(
                "Venturi closed-loop vs open-loop scrub on the same discharge. "
                "Negative Δ P_dis means control reduced disruption probability."
            ),
            metrics=[
                PerformanceMetric("Mean P_dis (open)", cf.mean_p_dis_open),
                PerformanceMetric("Mean P_dis (closed)", cf.mean_p_dis_closed),
                PerformanceMetric("Δ P_dis", cf.delta_p_dis, note="closed − open"),
                PerformanceMetric("Uniformity (open)", cf.mean_uniformity_open),
                PerformanceMetric("Uniformity (closed)", cf.mean_uniformity_closed),
                PerformanceMetric("Δ uniformity", cf.delta_uniformity, note="closed − open"),
                PerformanceMetric(
                    "ODL onset",
                    cf.first_odl_onset_s if cf.first_odl_onset_s is not None else "—",
                    unit="s",
                ),
                PerformanceMetric(
                    "First action",
                    cf.first_action_s if cf.first_action_s is not None else "—",
                    unit="s",
                ),
                PerformanceMetric(
                    "Lead time",
                    cf.lead_time_s if cf.lead_time_s is not None else "—",
                    unit="s",
                    note="action before label",
                ),
            ],
        ),
        PerformanceSection(
            title="Continuum & filament",
            metrics=[
                PerformanceMetric("P_rad (bremsstrahlung)", report.radiance_p_rad_mw, unit="MW"),
                PerformanceMetric(
                    "Filament pitch",
                    float(report.filament.get("pitch_rad", 0.0)),
                    unit="rad",
                ),
                PerformanceMetric(
                    "Filament length",
                    float(report.filament.get("length", 0.0)),
                ),
                PerformanceMetric("Device proxy", str(report.filament.get("device", "—"))),
            ],
        ),
        PerformanceSection(
            title="Closed-loop scrub summary",
            metrics=[
                PerformanceMetric("Frames", report.n_frames),
                PerformanceMetric(
                    "ODL label rate",
                    report.odl_label_rate if report.odl_label_rate is not None else "—",
                ),
                PerformanceMetric("Mean disruption", float(closed.get("mean_disruption", 0.0))),
                PerformanceMetric("Mean HELIX SNR", float(closed.get("mean_snr", 0.0))),
                PerformanceMetric("Final fusion score", float(closed.get("final_score", 0.0))),
            ],
        ),
    ]
    return PerformanceReport(
        title="fuselk Shot Performance Report",
        subject=f"Shot `{report.shot_id}` · device {report.device}",
        generated_at=report.generated_at or _now(),
        version=version,
        thesis=getattr(
            report,
            "thesis",
            "Shot Workbench: labels, HELIX, disruption, Venturi, and conserved P_rad on one clock.",
        ),
        sections=sections,
        tags=["workbench", "counterfactual", "odl", str(report.shot_id)],
    )


def from_odl_benchmark(report: Any, *, version: str) -> PerformanceReport:
    shots = list(getattr(report, "shots", []) or [])
    top = sorted(shots, key=lambda s: s.auc_proxy, reverse=True)[:8]
    metrics = [
        PerformanceMetric("Shots scored", report.n_shots),
        PerformanceMetric("Mean AUC proxy", report.mean_auc_proxy),
        PerformanceMetric("Mean P_dis", report.mean_p_dis),
        PerformanceMetric("corr(label, P_dis)", report.correlation_label_pdis),
    ]
    per_shot = [
        PerformanceMetric(
            s.shot_id,
            s.auc_proxy,
            note=f"P_dis={s.mean_p_dis:.3f} label_rate={s.odl_label_rate:.3f}",
        )
        for s in top
    ]
    return PerformanceReport(
        title="fuselk ODL Benchmark Performance Report",
        subject="MIT Open Density Limit (C-Mod) public benchmark",
        generated_at=_now(),
        version=version,
        thesis=(
            "Public ODL labels scored against fuselk disruption probability — "
            "no MDSplus credentials required."
        ),
        sections=[
            PerformanceSection(title="Aggregate", metrics=metrics),
            PerformanceSection(
                title="Top shots by AUC proxy",
                metrics=per_shot,
                narrative="Higher AUC proxy = better separation of density-limit vs stable phases.",
            ),
        ],
        tags=["odl", "benchmark", "disruption"],
    )


def from_fusion_cell(report: Any, *, version: str, steps: int | None = None) -> PerformanceReport:
    d = report.to_dict() if hasattr(report, "to_dict") else dict(report)
    fuel = d.get("fuel_cycle") or {}
    muon = d.get("muon_cycle") or {}
    subject = "Synthetic / reactor run"
    if steps is not None:
        subject = f"{subject} · {steps} steps"
    return PerformanceReport(
        title="fuselk FusionCell Performance Report",
        subject=subject,
        generated_at=_now(),
        version=version,
        thesis="Closed VISION loop KPIs: fuel cycle, muon trifecta, HELIX-driven control score.",
        sections=[
            PerformanceSection(
                title="Composite",
                metrics=[
                    PerformanceMetric("Fusion score", float(d.get("fusion_score", 0.0))),
                ],
            ),
            PerformanceSection(
                title="Fuel cycle",
                metrics=[
                    PerformanceMetric("TBR", float(fuel.get("tritium_breeding_ratio", 0.0))),
                    PerformanceMetric("Peclet", float(fuel.get("peclet_number", 0.0))),
                ],
            ),
            PerformanceSection(
                title="Muon cycle",
                metrics=[
                    PerformanceMetric("Fusions / muon", float(muon.get("fusions_per_muon", 0.0))),
                    PerformanceMetric(
                        "Literature aligned",
                        str(muon.get("literature_aligned", "-")),
                    ),
                ],
            ),
        ],
        tags=["fusion_cell", "kpis"],
    )


def from_reactor_run(run: Any, *, version: str, shot_id: str | None = None) -> PerformanceReport:
    report = run.to_report() if hasattr(run, "to_report") else dict(run)
    subject = f"Reactor run · score {getattr(run, 'final_score', report.get('final_score', 0)):.3f}"
    if shot_id:
        subject = f"Shot `{shot_id}` · {subject}"
    return PerformanceReport(
        title="fuselk Reactor Performance Report",
        subject=subject,
        generated_at=_now(),
        version=version,
        thesis="ReactorCell scrub KPIs after HELIX -> disruption -> Venturi closed loop.",
        sections=[
            PerformanceSection(
                title="Run summary",
                metrics=[
                    PerformanceMetric("Final score", float(getattr(run, "final_score", 0.0))),
                    PerformanceMetric("Steps", len(getattr(run, "steps", []) or [])),
                ],
            ),
            PerformanceSection(
                title="Report fields",
                metrics=[
                    PerformanceMetric(k, v if isinstance(v, int | float | str) else str(v))
                    for k, v in report.items()
                    if k not in ("steps", "actions")
                ][:12],
            ),
        ],
        tags=["reactor", "performance"] + ([shot_id] if shot_id else []),
    )
